
version: '3.8'
services:
  bot:
    container_name: beerbot_backend
    build: 
      context: ./bot
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      METRICS_PORT: 9090
      SHUTDOWN_TIMEOUT: 5s
      DB_PATH: /data/beerbot.db
    volumes:
      - ./bot/data:/data
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:9090/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
