version: '3.8'
services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - APP_TOKEN=${APP_TOKEN}
      - CHANNEL=${CHANNEL}
      - API_TOKEN=${API_TOKEN}
    volumes:
      - ./:/src:cached
      - ./data:/data
    ports:
      - "8080:8080"
    command: ["-db", "/data/bot.db", "-bot-token", "${BOT_TOKEN}", "-app-token", "${APP_TOKEN}", "-channel", "${CHANNEL}", "-api-token", "${API_TOKEN}"]
    restart: unless-stopped