version: '3.8'
services:
  test:
    image: golang:1.23
    working_dir: /src
    volumes:
      - ./:/src:cached
    command: ["/bin/sh", "-c", "apt-get update && apt-get install -y build-essential libsqlite3-dev git && go get github.com/mattn/go-sqlite3 github.com/slack-go/slack@latest github.com/slack-go/slack/socketmode@latest && go mod tidy && go test ./..."]
