name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        working-directory: ./bot
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache-dependency-path: ./bot/go.sum
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libsqlite3-dev
          go mod download
      - name: Run unit tests
        run: go test ./...
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.59.0
          working-directory: bot
          args: --timeout=10m --verbose
          skip-cache: false
          skip-pkg-cache: false
          skip-build-cache: false
